server:
  port: 8080
spring:
  application:
    name: springboot-redis-demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/k15?serverTimezone=UTC
    password: root
    username: root

  redis:
    host: 192.168.128.128
    port: 6379
